-- Reproducible baseline for the patient-facing cloud copy.
-- CREATE IF NOT EXISTS makes this safe for the existing project.

create table if not exists public.cloud_patients (
  cloud_id text primary key,
  birth_year integer not null,
  trend_data jsonb not null default '[]'::jsonb,
  last_updated timestamptz default now(),
  display_name text default '',
  historical_reports jsonb default '[]'::jsonb,
  password_hash text,
  salt text,
  temp_pw_hash text,
  birth_date text
);

create table if not exists public.cloud_clinical_rules (
  rule_key text primary key,
  rule_value text not null,
  unit text,
  description text,
  updated_at timestamptz default now()
);

create table if not exists public.cloud_access_logs (
  id integer generated by default as identity primary key,
  cloud_id text,
  display_name text,
  action text,
  access_time timestamptz default current_timestamp
);

create table if not exists public.cloud_shares (
  share_id uuid primary key default gen_random_uuid(),
  patient_ids jsonb not null,
  birth_years jsonb not null default '[]'::jsonb,
  require_verification boolean default true,
  expires_at timestamptz not null,
  created_at timestamptz default now()
);

alter table public.cloud_patients enable row level security;
alter table public.cloud_clinical_rules enable row level security;
alter table public.cloud_access_logs enable row level security;
alter table public.cloud_shares enable row level security;

grant all on public.cloud_patients, public.cloud_clinical_rules, public.cloud_access_logs, public.cloud_shares to service_role;
